---
report_title: "Stock Status Update of Atlantic Halibut (Hippoglossus hippoglossus) on the Scotian Shelf and Southern Grand Banks in NAFO Divisions 3NOPs4VWX5Zc"
report_year: "2024"
release_month: "December"
report_number: "XXX"
meeting_date: "December 10, 2024"
region: "Maritimes Region"
phone: "(902) 426-9920"
email: "MaritimesRAP.XMAR@dfo-mpo.gc.ca"
csa_address: "Fisheries and Oceans Canada
Bedford Institute of Oceanography
1 Challenger Drive, PO Box 1006
Dartmouth, Nova Scotia B2Y 4A2"
report_title_french: "Mise à jour de l'état du stock de flétan atlantique (Hippoglossus hippoglossus) du plateau néo-écossais et du sud du Grand Banc dans les divisions 3NOPs4VWX5Zc de l'OPANO pour 2024"
inuktitut_citation: " "
context: |
  Fisheries and Oceans Canada (DFO) Resource Management (RM) has requested Science advice on the status of the Scotian Shelf and southern Grand Banks (3NOPs4VWX5Zc) Atlantic halibut (Hippoglossus hippoglossus) stock based on the articulated harvest control rule adopted at the Scotia-Fundy Groundfish Advisory Committee (SFGAC) meeting in March 2022. A new assessment model was developed for this stock in 2022 (DFO 2024a) and closed-loop simulation was used to evaluate harvest control rules (Johnson et al. 2024).Full assessments for this stock are carried out every five years with stock status updates in the intervening years. The next framework assessment is scheduled for 2026. This Science Response Report results from the regional peer review of December 10th, 2024 on the Stock Status Update of Atlantic halibut (Hippoglossus hippoglossus) on the Scotian Shelf and southern Grand Banks in NAFO Divisions 3NOPs4VWX5Zc for 2024. 
output:
 csasdown::fsar_word
link-citations: true
bibliography: bib/refs.bib
csl: csl/csas.csl
# End of options to set
title: "Stock Status Update of Atlantic Halibut"
knit: (function(input, ...) {
       csasdown::render_sar()
      })
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.path = "knitr-figs-docx/",
  fig.asp = 0.618,
  fig.width = 7,
  echo = FALSE,
  dev = "png",
  dpi = 180
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(ggplot2)
#library(rosettafish)
library(csasdown)
library(ROracle)
library(devtools)
library(PBSmapping)
source(file.path(getwd(), "directories.r"))
source(file.path(wd, "passwords.r")) 

ds_all <- Mar.datawrangling::load_datasources()

devtools::load_all(".")

bins=seq(0,260,5)
# labelled by upper bound
Assessment.Year <-2024


```
