---
title: "Canada-US Negotiations"
author: "Brad"
date: "2024-10-21"
output: html_document
---

```{r setup, include=FALSE}
library(devtools)

# install_github("Maritimes/Mar.datawrangling")
#install_github("BradHubley/SpatialHub")

library(Mar.datawrangling)
 library(SpatialHub)
library(PBSmapping)
library(sp)

source(file.path(getwd(), "directories.r"))
#datadir="C:/Users/hubleyb/Documents/Halibut/data"
#wd="C:/Users/hubleyb/Documents/Halibut/Git/DataInputs/"
#datadir="C:/Users/harperd/Documents/Halibut/RDataVault"
#wd="C:/Users/harperd/Documents/Halibut/GitDataInputs/DataInputs/"

source(file.path(wd, "passwords.r")) 
ds_all <- Mar.datawrangling::load_datasources()
devtools::load_all(".")

# source(calcAreaFrance.r)
# png(paste0(filen,".png"), width = wd, height = ht,units='in',pointsize=12, res=300,type='cairo')

```

```{r}
CanUSProp<-read.csv(file.path(datadir,"Regional_Proportions 1.csv"))

with(CanUSProp,tapply(Proportion,Index_Region,mean))
```

# Stratified Random Survey
```{r}

load(file.path(datadir,"Survey","SurveyStrata2022.RData"))
RandomSurveySets<-RandomSurveyData(sp=30,datadir=datadir,by.sex=F,add.LF=F)
yrs<-unique(RandomSurveySets$YEAR)

 bioMap(xlim=c(-60,-53), ylim=c(43,48),poly.lst = list(surveyStrataPolyLL,props), plot.rivers=F, isobaths = NULL,mapRes="MR",LT=T)
 for(i in 1:length(yrs)){
   with(subset(RandomSurveySets,YEAR==yrs[i]),points(LONG1,LAT1,pch=21,bg=i+1))
   
 }
 
 legend("bottomright",legend=yrs,pch=21,pt.bg=1:length(yrs)+1)


```



## calc stratified survey estimate for whole stock area and just Scotian Shelf
```{r}

# source(calcAreaFrance.r) #script that calculates strata areas inside SPM EEZ and saves them as SPMareas.csv

 HSRandom_Index<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:2022, output = 'stratified.estimate')
 HSRandom_Index_SSS<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:2022, output = 'stratified.estimate', select.strata=c(11, 12, 13, 21, 22, 23, 31, 32, 33, 34))
HSRandom_Index_3NOP<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:2022, output = 'stratified.estimate', select.strata=c(41, 42, 43, 44, 51, 52, 53))
 HSRandom_Index_NRA<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:2022, output = 'stratified.estimate', AltArea="NRA")
 
 library(mratios)
pSS<- ttestratio(HSRandom_Index_SSS$N,HSRandom_Index$N)
pNRA<- ttestratio(HSRandom_Index_NRA$B,HSRandom_Index$B)
p3NOP<- ttestratio(HSRandom_Index_3NOP$B - HSRandom_Index_NRA$B,HSRandom_Index$B)
pUS<-ttestratio(CanUSProp$Index_Estimate[CanUSProp$Index_Region=="USA"],CanUSProp$Total_Estimate[CanUSProp$Index_Region=="USA"])
pCan<-ttestratio(CanUSProp$Index_Estimate[CanUSProp$Index_Region=="Canada"],CanUSProp$Total_Estimate[CanUSProp$Index_Region=="Canada"])

pCan<-ttestratio(CanUSProp$Index_Estimate[CanUSProp$Index_Region=="Canada"],CanUSProp$Total_Estimate[CanUSProp$Index_Region=="Canada"])


pCan$estimate[3]
pCan$conf.int

pUS$estimate[3]
pUS$conf.int

pSS$estimate[3]
pSS$conf.int

pNRA$estimate[3]
pNRA$conf.int

p3NOP$estimate[3]
p3NOP$conf.int
```

# a plot
```{r}
png(file.path(wd,'figures',"StratifiedSurveyBiomassCanadaFrance.png"), width =8, height = 6,units='in',pointsize=12, res=300,type='cairo')
par(mfcol=c(2,1), mar = c(0,4,0,0.5), omi = c(0.5, 0.25, 0.5, 0.25),las=1)
 
 plot(B/10^6~Year,HSRandom_Index,type='b',pch=15,col='red',ylim=c(0,60), ylab="Stratified Biomass  (kt)")
  lines((B+Bse)/10^6~Year,HSRandom_Index,lty=2,col='red')
  lines((B-Bse)/10^6~Year,HSRandom_Index,lty=2,col='red')
legend('bottomright',c("3NOPs4VWX5Zc","St.Pierre and Miquelon EEZ"),pch=15:16,col=c('red','blue'))
 plot(B/10^6~Year,HSRandom_Index_SPM,type='b',pch=16,col='blue',ylim=c(0,1.5), ylab="Stratified Biomass  (kt)")
  lines((B+Bse)/10^6~Year,HSRandom_Index_SPM,lty=2,col='blue')
  lines((B-Bse)/10^6~Year,HSRandom_Index_SPM,lty=2,col='blue')

```



### again for the NRA
# Stratified Random Survey
```{r}

load(file.path(datadir,"Survey","SurveyStrata2022.RData"))
RandomSurveySets<-RandomSurveyData(sp=30,datadir=datadir,by.sex=F,add.LF=F)
yrs<-unique(RandomSurveySets$YEAR)

 bioMap(xlim=c(-53,-47), ylim=c(42,47),poly.lst = list(surveyStrataPolyLL,props), plot.rivers=F, isobaths = NULL,mapRes="MR",LT=T)
 for(i in 1:length(yrs)){
   with(subset(RandomSurveySets,YEAR==yrs[i]),points(LONG1,LAT1,pch=21,bg=i+1))
   
 }
 
 legend("bottomright",legend=yrs,pch=21,pt.bg=1:length(yrs)+1)


```



## calc stratified survey estimate for whole stock area and just for NRA
```{r}

# source(calcAreaFrance.r) #script that calculates strata areas inside SPM EEZ and saves them as SPMareas.csv

 HSRandom_Index<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:2022, output = 'stratified.estimate' )
 HSRandom_Index_NRA<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:2022, output = 'stratified.estimate', AltArea="NRA")


 
 # total allowable catch for 3NOPs4VWX5Zc 
 TAC<-c(3621,4164,4789,5507,5445,4807)
 
 # what TAC should be for SPM if proportional to stratified survey biomass estimate
 round(HSRandom_Index_NRA$B/HSRandom_Index$B * TAC)
 
 library(mratios)
 ttestratio(HSRandom_Index_NRA$B,HSRandom_Index$B)


```

# a plot
```{r}
png(file.path(wd,'figures',"StratifiedSurveyBiomassCanadaFranceNRA.png"), width =8, height = 6,units='in',pointsize=12, res=300,type='cairo')
par(mfcol=c(2,1), mar = c(0,4,0,0.5), omi = c(0.5, 0.25, 0.5, 0.25),las=1)
 
 plot(B/10^6~Year,HSRandom_Index,type='b',pch=15,col='red',ylim=c(0,60), ylab="Stratified Biomass  (kt)")
  lines((B+Bse)/10^6~Year,HSRandom_Index,lty=2,col='red')
  lines((B-Bse)/10^6~Year,HSRandom_Index,lty=2,col='red')
legend('bottomright',c("3NOPs4VWX5Zc","NRA"),pch=15:16,col=c('red','blue'))
 plot(B/10^6~Year,HSRandom_Index_NRA,type='b',pch=16,col='blue',ylim=c(0,10), ylab="Stratified Biomass  (kt)")
  lines((B+Bse)/10^6~Year,HSRandom_Index_NRA,lty=2,col='blue')
  lines((B-Bse)/10^6~Year,HSRandom_Index_NRA,lty=2,col='blue')

```


```{r}
HSRandom_Index<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:2022, output = 'stratified.estimate')
load("~/Halibut/git/DataInputs/inst/Nti.rdata")

B3Ps<-c()
for(i in 1:6){
  B3Ps<-with(subset(Nti[[i]],PID%in%(41:44)),sum(Bh*area))
}

B3Ps/HSRandom_Index$B
HSRandom_Index_SPM$B/B3Ps
```
## what % of Landings in the NRA
```{r}
x<-c(-55,-45)
y<-c(42,47)

MARFISdata<-getMARFISdata(datadir,sp=130)
MARFISdata<-subset(MARFISdata,YEAR>2020)
EEZ3NO<-clipPolys(subset(EEZ,PID==2),xlim=x,ylim=y)
MARFISdata3NO<-subset(MARFISdata,LATITUDE<y[2]&LATITUDE>y[1]&LONGITUDE<x[2]&LONGITUDE>x[1])
MARFISdata3NO$EID<-1:nrow(MARFISdata3NO)
key<-findPolys(with(MARFISdata3NO,data.frame(EID,X=LONGITUDE,Y=LATITUDE)),EEZ3NO)

MARFISdataNRA<-subset(MARFISdata3NO,!EID%in%key$EID)

 sum(MARFISdataNRA$RND_WEIGHT_KGS)/sum(MARFISdata$RND_WEIGHT_KGS[!is.na(MARFISdata$LATITUDE)],na.rm=T)*100
 
 
```
```{r}
ComIndex<-CommercialIndexData(datadir=datadir,bins=bins,by.sex=F,add.portsampling=F,add.LF = F)
ComIndex<-subset(ComIndex,NAFAREA_ID=="3PS")
ComIndex$KgPKH<-ComIndex$EST_COMBINED_WT/ComIndex$NUM_HOOK_HAUL*1000
ComIndex$Q<-quarter(ComIndex$DATE_TIME1)
CI<-with(ComIndex,tapply(KgPKH,YEAR, mean, na.rm=T))
plot(as.numeric(names(CI)),CI,xlab = '',ylab = 'KgPKH',ylim=c(0,900),type='b',pch=16)



```



```{r}

NAFO <- sf::st_read(file.path(datadir,"Mapping","NAFODivisions","Divisions.shp"))

xl=c(-68,-47)
yl=c(41,48)    
  Yrs = 2017:2023        
  i=Yrs
  
#for(i in Yrs){
  
  
	# interpolate biomass from stratified random survey
  RandomSurvey<-RandomSurveyData(sp=30,datadir=datadir,by.sex=F)
  interp.data<-subset(RandomSurvey,YEAR%in%i,c('FISHSET_ID','LONG1','LAT1','EST_COMBINED_WT'))
    interp.data<-	subset(interp.data,LAT1>yl[1]&LAT1<yl[2]&LONG1>xl[1]&LONG1<xl[2])	
		#interp.data$EST_COMBINED_WT[is.na(interp.data$EST_COMBINED_WT)]<-0
		hal.contours<-interpolation(interp.data,ticks='define',place=3,nstrata=5,str.min=0,interp.method='gstat',blank=T,blank.dist=0.5,res=0.1,smooth=F,idp=3.5)

		# define contour lines
		print(hal.contours$str.def)
		lvls=c(1, 20, 50, 100, 200, 500, 1000)

	  cont.lst<-contourGen(hal.contours$image.dat,lvls,col="YlGn",colorAdj=1)
	  cont.lst[[1]]<-joinPolys(cont.lst[[1]],subset(surveyPolyLL,SID==1),operation="INT")
	  Y<-ifelse(length(i)>1,paste(min(i),max(i),sep='-'),i)
	  
	  
    png(file.path(wd,'figures',paste0('StratfiedRandomSurveyMapBiomass',Y,'.png')),width=10,height=7,units='in',pointsize=12, res=300,type='cairo')
                             
    SpatialHub::bioMap(xlim = xl, ylim = yl,contours=cont.lst, mapRes="MR", title = paste("Stratified Random Survey",Y))
    plot(st_geometry(NAFO),add=T)

 # text(st_coordinates(NAFO)[,1], st_coordinates(NAFO)[,2],NAFO$ZONE)
    PBSmapping::addLines(subset(surveyPolyLL,SID==1),col=rgb(1,0,0,0.5))
    points(LAT1~LONG1,interp.data,pch=21,bg=rgb(1,1,0,1),cex=0.5)
    contLegend('topleft',lvls=lvls,Cont.data = cont.lst[[2]], cex=0.8, title='Kg Halibut / Set')
    text(st_coordinates(st_centroid(NAFO)), labels = NAFO$ZONE, cex = 1, pos=2,col='black')

#addPolys(BO1,density=20,col='black')
#addPolys(BO2,density=20,col='black')

dev.off()
#}

  
  
```
