---
title: "CatchComposition"
author: "Brad"
date: "February 4, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(devtools)
#install_github("Maritimes/Mar.datawrangling")
 library(Mar.datawrangling)
 library(tidyverse)
library(SpatialHub)

#install_github("BradHubley/SpatialHub")
source(file.path(getwd(), "directories.r"))
#datadir="C:/Users/hubleyb/Documents/Halibut/data"
#wd="C:/Users/hubleyb/Documents/Halibut/Git/DataInputs/"
#datadir="C:/Users/harperd/Documents/Halibut/RDataVault"
#wd="C:/Users/harperd/Documents/Halibut/GitDataInputs/DataInputs/"

source(file.path(wd, "passwords.r")) 
ds_all <- Mar.datawrangling::load_datasources()
devtools::load_all(".")

NAFOunits<-list(
nafo3 = c( "3N", "3NA", "3NB", "3NC", "3ND", "3NE", "3NF", "3O", "3OA", "3OC", "3OD", "3OE", "3PN", "3PS"),
nafo4 = c("4VB", "4VC", "4VN", "4VS", "4W", "4WD", "4WE", "4WF", "4WG", "4WH", "4WJ", "4WK", "4WL", "4WM", "4X", "4XL", "4XM", "4XN", "4XO", "4XP", "4XQ", "4XR", "4XS", "5YB", "5ZJ", "5ZM", "5ZN"))

bins=seq(0,260,5)

```

## Update data from database 

```{r }


# Update data from database 

# Mar.datawrangling::get_data(db='isdb',data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)
# open and check setprofile_wide to confirm that you have year, latitude & longitude

# Mar.datawrangling::get_data_custom(schema="observer", data.dir = datadir, tables = c("ISFISHLENGTHS","ISSAMPLES"), usepkg = "roracle", fn.oracle.dsn= "PTRAN", fn.oracle.username=uid, fn.oracle.password =pwd)

#get_ps_data(data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)

```


## 

```{r,  echo=FALSE}
Yrs=1978:2020

 nafo3 = c( "3N", "3NA", "3NB", "3NC", "3ND", "3NE", "3NF", "3O", "3OA", "3OC", "3OD", "3OE", "3PN", "3PS", "3U")
 nafo4 = c("4V","4VB", "4VC", "4VN", "4VNW", "4VS", "4VSB", "4VSC","4VSW","4VW","4VX", "4W", "4WD", "4WE", "4WF", "4WG", "4WH", "4WJ", "4WK", "4WL", "4WM","4WX","4XMNOPQ", "4X", "4XL", "4XM", "4XN", "4XO", "4XP", "4XQ", "4XR", "4XU", "4XS", "4XRS", "5YB", "5ZJ", "5ZM", "5ZN","5ZEJ")

PortData<-PortSampleData(datadir=datadir,by.sex=T, bins=bins)
portNAFO3OT=constructLF(LFdata=subset(PortData,NAFO%in%nafo3&GEAR=="OT"),bins=bins, Yrs = Yrs)
portNAFO4OT=constructLF(LFdata=subset(PortData,NAFO%in%nafo4&GEAR=="OT"),bins=bins, Yrs = Yrs)
portNAFO3LL=constructLF(LFdata=subset(PortData,NAFO%in%nafo3&GEAR=="LL"),bins=bins, Yrs = Yrs)
portNAFO4LL=constructLF(LFdata=subset(PortData,NAFO%in%nafo4&GEAR=="LL"),bins=bins, Yrs = Yrs)


ObserverData<-ObsData(datadir=datadir,by.sex=T, bins=bins)
obsNAFO3OT=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo3&GEAR=="OT"),bins=bins, Yrs = Yrs)
obsNAFO4OT=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo4&GEAR=="OT"),bins=bins, Yrs = Yrs)
obsNAFO3LL=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo3&GEAR=="LL"),bins=bins, Yrs = Yrs)
obsNAFO4LL=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo4&GEAR=="LL"),bins=bins, Yrs = Yrs)


LLNafo4_males<-getNAL(portNAFO4LL,sex=1)+getNAL(obsNAFO4LL,sex=1)
LLNafo4_females<-getNAL(portNAFO4LL,sex=2)+getNAL(obsNAFO4LL,sex=2)
LLNafo4_combined<-getNAL(portNAFO4LL,sex='all')+getNAL(obsNAFO4LL,sex='all')
LLNafo4_unsexed<-getNAL(obsNAFO4LL,sex=0)

LLNafo3_males<-getNAL(portNAFO3LL,sex=1)+getNAL(obsNAFO3LL,sex=1)
LLNafo3_females<-getNAL(portNAFO3LL,sex=2)+getNAL(obsNAFO3LL,sex=2)
LLNafo3_combined<-getNAL(portNAFO3LL,sex='all')+getNAL(obsNAFO3LL,sex='all')
LLNafo3_unsexed<-getNAL(obsNAFO3LL,sex=0)

OTNafo4_males<-getNAL(portNAFO4OT,sex=1)+getNAL(obsNAFO4OT,sex=1)
OTNafo4_females<-getNAL(portNAFO4OT,sex=2)+getNAL(obsNAFO4OT,sex=2)
OTNafo4_combined<-getNAL(portNAFO4OT,sex='all')+getNAL(obsNAFO4OT,sex='all')
OTNafo4_unsexed<-getNAL(obsNAFO4OT,sex=0)

OTNafo3_males<-getNAL(portNAFO3OT,sex=1)+getNAL(obsNAFO3OT,sex=1)
OTNafo3_females<-getNAL(portNAFO3OT,sex=2)+getNAL(obsNAFO3OT,sex=2)
OTNafo3_combined<-getNAL(portNAFO3OT,sex='all')+getNAL(obsNAFO3OT,sex='all')
OTNafo3_unsexed<-getNAL(obsNAFO3OT,sex=0)

Fishery_Lengths<-list(LLNafo4_males=LLNafo4_males,
                      LLNafo4_females=LLNafo4_females,
                      LLNafo4_combined=LLNafo4_combined,
                      LLNafo4_unsexed=LLNafo4_unsexed, 
                      LLNafo3_males=LLNafo3_males,
                      LLNafo3_females=LLNafo3_females,
                      LLNafo3_combined=LLNafo3_combined,
                      LLNafo4_unsexed=LLNafo4_unsexed,  
                      OTNafo4_males=OTNafo4_males,
                      OTNafo4_females=OTNafo4_females,
                      OTNafo4_combined=OTNafo4_combined, 
                      OTNafo4_unsexed=OTNafo4_unsexed, 
                      OTNafo3_males=OTNafo3_males,
                      OTNafo3_females=OTNafo3_females,
                      OTNafo3_combined=OTNafo3_combined, 
                      OTNafo3_unsexed=OTNafo3_unsexed) 


```



# Plots
```{r}

BubblePlotLF(Fishery_Lengths,bins=bins,yrs=1978:2020,path=file.path(wd,'figures'),filen='Commercial',inches=0.3)

    Yrs1=2006:2020
    pdf(file.path(wd,"figures","CommercialLengthCompData.pdf"), width = 8, height = 11)
      
BarPlotLF( obsNAFO4LL[which(names( obsNAFO4LL)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="obsNAFO4LL")
BarPlotLF(portNAFO4LL[which(names(portNAFO4LL)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="portNAFO4LL")
BarPlotLF( obsNAFO4OT[which(names( obsNAFO4OT)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="obsNAFO4OT")
BarPlotLF(portNAFO4OT[which(names(portNAFO4OT)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="portNAFO4OT")
BarPlotLF( obsNAFO3LL[which(names( obsNAFO3LL)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="obsNAFO3LL")
BarPlotLF(portNAFO3LL[which(names(portNAFO3LL)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="portNAFO3LL")
BarPlotLF( obsNAFO3OT[which(names( obsNAFO3OT)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="obsNAFO3OT")
BarPlotLF(portNAFO3OT[which(names(portNAFO3OT)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="portNAFO3OT")
    
    dev.off()


    Yrs1=1991:2005
    pdf(file.path(wd,"figures","CommercialLengthCompData2.pdf"), width = 8, height = 11)
      
BarPlotLF( obsNAFO4LL[which(names( obsNAFO4LL)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="obsNAFO4LL")
BarPlotLF(portNAFO4LL[which(names(portNAFO4LL)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="portNAFO4LL")
BarPlotLF( obsNAFO4OT[which(names( obsNAFO4OT)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="obsNAFO4OT")
BarPlotLF(portNAFO4OT[which(names(portNAFO4OT)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="portNAFO4OT")
BarPlotLF( obsNAFO3LL[which(names( obsNAFO3LL)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="obsNAFO3LL")
BarPlotLF(portNAFO3LL[which(names(portNAFO3LL)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="portNAFO3LL")
BarPlotLF( obsNAFO3OT[which(names( obsNAFO3OT)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="obsNAFO3OT")
BarPlotLF(portNAFO3OT[which(names(portNAFO3OT)%in%Yrs1)], yrs=Yrs1, sample.size='calculate', rel=F,graphic='off',toplab="portNAFO3OT")
    
    dev.off()


```
Lingbo's maturity project


```{r}
bins=seq(0,260,5)
Yrs=2010:2020

 nafo3NOP = c( "3N", "3NA", "3NB", "3NC", "3ND", "3NE", "3NF", "3O", "3OA", "3OC", "3OD", "3OE", "3PS", "3U")
 nafo4VW = c("4V","4VB", "4VC", "4VN", "4VNW", "4VS", "4VSB", "4VSC","4VSW","4VW","4VX", "4W", "4WD", "4WE", "4WF", "4WG", "4WH", "4WJ", "4WK", "4WL", "4WM","4WX")
 
 nafo4X = c("4XMNOPQ", "4X", "4XL", "4XM", "4XN", "4XO", "4XP", "4XQ", "4XR", "4XU", "4XS", "4XRS")


PortData<-PortSampleData(datadir=datadir,by.sex=T, bins=bins)

portNAFO3NOP=constructLF(LFdata=subset(PortData,NAFO%in%nafo3NOP&GEAR=="LL"),bins=bins, Yrs = Yrs)
portNAFO4VW=constructLF(LFdata=subset(PortData,NAFO%in%nafo4VW&GEAR=="LL"),bins=bins, Yrs = Yrs)
portNAFO4X=constructLF(LFdata=subset(PortData,NAFO%in%nafo4X&GEAR=="LL"),bins=bins, Yrs = Yrs)

BarPlotLF(portNAFO3NOP, yrs=Yrs, sample.size='calculate', rel=F, filen=file.path(wd,"figures","port3NOP"))
BarPlotLF(portNAFO4VW, yrs=Yrs, sample.size='calculate', rel=F, filen=file.path(wd,"figures","port4VW"))
BarPlotLF(portNAFO4X, yrs=Yrs, sample.size='calculate', rel=F, filen=file.path(wd,"figures","port4X"))

ObserverData<-ObsData(datadir=datadir,by.sex=T, bins=bins)

obsNAFO3NOP=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo3NOP&GEAR=="LL"),bins=bins, Yrs = Yrs)
obsNAFO4VW=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo4VW&GEAR=="LL"),bins=bins, Yrs = Yrs)
obsNAFO4X=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo4X&GEAR=="LL"),bins=bins, Yrs = Yrs)

BarPlotLF(obsNAFO3NOP, yrs=Yrs, sample.size='calculate', rel=F, filen=file.path(wd,"figures","obs3NOP"))
BarPlotLF(obsNAFO4VW, yrs=Yrs, sample.size='calculate', rel=F, filen=file.path(wd,"figures","obs4VW"))
BarPlotLF(obsNAFO4X, yrs=Yrs, sample.size='calculate', rel=F, filen=file.path(wd,"figures","obs4X"))

```

# map of observer data
```{r}
bioMap()
with(subset(ObserverData,YEAR%in%Yrs),points(LONGITUDE,LATITUDE,pch='.',col=rgb(1,0,0,0.1)))


bioMap(xlim=c(-66,-65),ylim=c(42.5,43), isobaths = seq(10, 1000, 10))
with(subset(ObserverData,YEAR%in%Yrs),points(LONGITUDE,LATITUDE,pch=16,cex=0.5,col=rgb(1,0,0,0.1)))


```


