---
title: "ModelRuns"
author: "Brad"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
library(devtools)
library(tidyverse)
source(file.path(getwd(), "directories.r"))
source(file.path(wd, "passwords.r")) 

scaldir<-file.path(datadir,"scal")
#scaldir<-"R:/Science/Population Ecology Division/Shared/Atlantic Halibut/Assessments & Updates/2021 Framework/Data/Model Inputs"
ds_all <- Mar.datawrangling::load_datasources()

devtools::load_all(".")


bins=seq(0,260,5)
# labelled by upper bound

```


## Update data from database 

```{r }


# Update data from database 

# Mar.datawrangling::get_data(db='isdb',data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)
# open and check setprofile_wide to confirm that you have year, latitude & longitude

# Mar.datawrangling::get_data_custom(schema="observer", data.dir = datadir, tables = c("ISFISHLENGTHS","ISSAMPLES"), usepkg = "roracle", fn.oracle.dsn= "PTRAN", fn.oracle.username=uid, fn.oracle.password =pwd)

#get_ps_data(data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)


# get_data(db='rv',data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)


```


# read in data from old inputs

```{r }
old_data_inputs<-getOldScalInputs(scaldir=scaldir)

# Old Model Starting parameters
#old_ipars<-lisread(file.path(scaldir,'scal_base.pin'))

```



# Output biological parameters table
```{r }
bioPars<-old_data_inputs[c("lInf_m","lInf_f","vonK_m","vonK_f","wt_a","wt_b","aMat_50","aMat_95","prior_initM","dM")]
bioPars$dM2<-bioPars$dM[3]
bioPars$dM<-bioPars$dM[1]
bioPars$wt_a=0.006803616
bioPars$wt_b=3.119924
bioParsTab<-tibble(data.frame(Parameter=names(bioPars),Value=unlist(bioPars)))
write.csv(bioParsTab,file.path(scaldir,"bioPars.csv"),row.names=F)

BiologicalParameters<-bioPars
BiologicalParameters$bins<-bins
```

#RV survey

```{r}

RVdata<-get4VWXRV(uid, pwd, use.local=T,datadir=datadir)
RVinputs<-prepRVdata(RVdata,bins=bins,years=1970:2020, raw=T)
RVinputs$NSRV_unsexed<-RVinputs$NSRV_combined-(RVinputs$NSRV_males+RVinputs$NSRV_females) # unsexed
NSRV_Index<-RVinputs$Index
NSRV_Lengths<-list(NSRV_males=RVinputs$NSRV_males,
                   NSRV_females=RVinputs$NSRV_females,
                   NSRV_combined=RVinputs$NSRV_combined,
                   NSRV_unsexed=RVinputs$NSRV_unsexed)

#BubblePlotLF(NSRV_Lengths,bins=bins,yrs=1970:2020,path=file.path(wd,'figures'),filen='RVSurvey',inches=0.3)


NLRV_Lengths<-read.csv(file.path(scaldir,"NLSurveyCAL.csv"))
row.names(NLRV_Lengths)<-NLRV_Lengths$year
NLRV_Lengths<-NLRV_Lengths[,-1]
names(NLRV_Lengths)<-paste0("L",bins[-1])


#BubblePlotLF(list(NLRV_Lengths),bins=bins,yrs=1996:2020,path=file.path(wd,'figures'),filen='NLRVSurvey',inches=0.3)


NLRV_Index<-rowSums(NLRV_Lengths)

```



#Halibut Survey Catch Composition
```{r}
  Yrs1 = 2000:2020        
  Yrs2 = 2017:2020        

  FixedSurvey <- FixedSurveyData(datadir=datadir, bins=bins,by.sex=T)
  RandomSurvey <- RandomSurveyData(datadir=datadir,bins=bins,by.sex=T)

  # Construct CLF
  FixedLF <- constructLF(LFdata=FixedSurvey,bins=bins, Yrs = Yrs1)
  RandomLF <- constructLF(LFdata=RandomSurvey,bins=bins, Yrs = Yrs2)

  # Fixed survey numbers at length    
  HSFixed_males<-getNAL(FixedLF,sex=1)
  HSFixed_females<-getNAL(FixedLF,sex=2)
  HSFixed_combined<-getNAL(FixedLF,sex='all')
  HSFixed_unsexed<-getNAL(FixedLF,sex=0)
  
  HSFixed_Lengths<-list(HSFixed_males=HSFixed_males,
                        HSFixed_females=HSFixed_females,
                        HSFixed_combined=HSFixed_combined,
                        HSFixed_unsexed=HSFixed_unsexed)
  
  # Random survey numbers at length    
  HSRandom_males<-getNAL(RandomLF,sex=1)
  HSRandom_females<-getNAL(RandomLF,sex=2)
  HSRandom_combined<-getNAL(RandomLF,sex='all')
  HSRandom_unsexed<-getNAL(RandomLF,sex=0)
  
  HSRandom_Lengths<-list(HSRandom_males=HSRandom_males,
                         HSRandom_females=HSRandom_females,
                         HSRandom_combined=HSRandom_combined,
                         HSRandom_unsexed=HSRandom_unsexed)
  
  HSRandom_Index<-data.frame(Year= 2017:2020,
                             Index= c(2.204668e-05, 3.263344e-05, 3.004447e-05, 1.819697e-05), 
                             se= c(1.075617e-06, 1.291483e-06, 1.437159e-06, 8.738080e-07))
  
  HSFixed_Index<-FixedSurveyIndex(datadir=datadir,yrs=1970:2020)


```

#Landings
```{r}
Landings_t<-read.csv(file.path(scaldir,"nafoSCAL.csv"))

```

#Fishery Catch Composition
```{r}
CCyrs=1978:2020

 nafo3 = c( "3N", "3NA", "3NB", "3NC", "3ND", "3NE", "3NF", "3O", "3OA", "3OC", "3OD", "3OE", "3PS", "3U")
 nafo4 = c("4V","4VB", "4VC", "4VN", "4VNW", "4VS", "4VSB", "4VSC","4VSW","4VW","4VX", "4W", "4WD", "4WE", "4WF", "4WG", "4WH", "4WJ", "4WK", "4WL", "4WM","4WX","4XMNOPQ", "4X", "4XL", "4XM", "4XN", "4XO", "4XP", "4XQ", "4XR", "4XU", "4XS", "4XRS", "5YB", "5ZJ", "5ZM", "5ZN","5ZEJ")

PortData<-PortSampleData(datadir=datadir,by.sex=T, bins=bins)
portNAFO3OT=constructLF(LFdata=subset(PortData,NAFO%in%nafo3&GEAR=="OT"),bins=bins, Yrs = CCyrs)
portNAFO4OT=constructLF(LFdata=subset(PortData,NAFO%in%nafo4&GEAR=="OT"),bins=bins, Yrs = CCyrs)
portNAFO3LL=constructLF(LFdata=subset(PortData,NAFO%in%nafo3&GEAR=="LL"),bins=bins, Yrs = CCyrs)
portNAFO4LL=constructLF(LFdata=subset(PortData,NAFO%in%nafo4&GEAR=="LL"),bins=bins, Yrs = CCyrs)

ObserverData<-ObsData(datadir=datadir,by.sex=T, bins=bins,min.length=0)
obsNAFO3OT=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo3&GEAR=="OT"),bins=bins, Yrs = CCyrs)
obsNAFO4OT=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo4&GEAR=="OT"),bins=bins, Yrs = CCyrs)
obsNAFO3LL=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo3&GEAR=="LL"),bins=bins, Yrs = CCyrs)
obsNAFO4LL=constructLF(LFdata=subset(ObserverData,NAFO%in%nafo4&GEAR=="LL"),bins=bins, Yrs = CCyrs)


LLNafo4_males<-getNAL(portNAFO4LL,sex=1)+getNAL(obsNAFO4LL,sex=1)
LLNafo4_females<-getNAL(portNAFO4LL,sex=2)+getNAL(obsNAFO4LL,sex=2)
LLNafo4_combined<-getNAL(portNAFO4LL,sex='all')+getNAL(obsNAFO4LL,sex='all')
LLNafo4_unsexed<-getNAL(obsNAFO4LL,sex=0)

LLNafo3_males<-getNAL(portNAFO3LL,sex=1)+getNAL(obsNAFO3LL,sex=1)
LLNafo3_females<-getNAL(portNAFO3LL,sex=2)+getNAL(obsNAFO3LL,sex=2)
LLNafo3_combined<-getNAL(portNAFO3LL,sex='all')+getNAL(obsNAFO3LL,sex='all')
LLNafo3_unsexed<-getNAL(obsNAFO3LL,sex=0)

OTNafo4_males<-getNAL(portNAFO4OT,sex=1)+getNAL(obsNAFO4OT,sex=1)
OTNafo4_females<-getNAL(portNAFO4OT,sex=2)+getNAL(obsNAFO4OT,sex=2)
OTNafo4_combined<-getNAL(portNAFO4OT,sex='all')+getNAL(obsNAFO4OT,sex='all')
OTNafo4_unsexed<-getNAL(obsNAFO4OT,sex=0)

OTNafo3_males<-getNAL(portNAFO3OT,sex=1)+getNAL(obsNAFO3OT,sex=1)
OTNafo3_females<-getNAL(portNAFO3OT,sex=2)+getNAL(obsNAFO3OT,sex=2)
OTNafo3_combined<-getNAL(portNAFO3OT,sex='all')+getNAL(obsNAFO3OT,sex='all')
OTNafo3_unsexed<-getNAL(obsNAFO3OT,sex=0)

Fishery_Lengths<-list(LLNafo4_males=LLNafo4_males,
                      LLNafo4_females=LLNafo4_females,
                      LLNafo4_combined=LLNafo4_combined,
                      LLNafo4_unsexed=LLNafo4_unsexed, 
                      LLNafo3_males=LLNafo3_males,
                      LLNafo3_females=LLNafo3_females,
                      LLNafo3_combined=LLNafo3_combined,
                      LLNafo4_unsexed=LLNafo4_unsexed,  
                      OTNafo4_males=OTNafo4_males,
                      OTNafo4_females=OTNafo4_females,
                      OTNafo4_combined=OTNafo4_combined, 
                      OTNafo4_unsexed=OTNafo4_unsexed, 
                      OTNafo3_males=OTNafo3_males,
                      OTNafo3_females=OTNafo3_females,
                      OTNafo3_combined=OTNafo3_combined, 
                      OTNafo3_unsexed=OTNafo3_unsexed) 

#BubblePlotLF(Fishery_Lengths,bins=bins,yrs=CCyrs,path=file.path(wd,'figures'),filen='Commercial',inches=0.3)

```

# Put it all together
```{r}

save(BiologicalParameters,NSRV_Index,NSRV_Lengths,NLRV_Index,NLRV_Lengths,HSFixed_Index,HSFixed_Lengths,HSRandom_Index,HSRandom_Lengths,Landings_t,Fishery_Lengths,file=file.path(scaldir,"SCALmodeldata.rdata"))

```


# Bubble plots
```{r}

BubblePlotLF(NSRV_Lengths,bins=bins,yrs=1970:2020,path=file.path(wd,'figures'),filen='NSRVSurvey',inches=0.3)
BubblePlotLF(list(NLRV_Lengths),bins=bins,yrs=1996:2019,path=file.path(wd,'figures'),filen='NLRVSurvey',inches=0.3)
BubblePlotLF(HSFixed_Lengths,bins=bins,yrs=2000:2020,path=file.path(wd,'figures'),filen='FixedSurvey',inches=0.3)
BubblePlotLF(HSRandom_Lengths,bins=bins,yrs=2017:2020,path=file.path(wd,'figures'),filen='RandomSurvey',inches=0.3)
BubblePlotLF(Fishery_Lengths,bins=bins,yrs=1978:2020,path=file.path(wd,'figures'),filen='Commercial',inches=0.3)

```


