---
title: "SurveyData"
author: "Brad"
date: "January 12, 2021"
output: html_document
---

```{r setup, include=FALSE}
library(devtools)
#install_github("Maritimes/Mar.datawrangling")
#install_github("Maritimes/Mar.bycatch")
 library(Mar.datawrangling)
 library(Mar.bycatch)
 library(tidyverse)

source(file.path(getwd(), "directories.r"))
#datadir="C:/Users/hubleyb/Documents/Halibut/data"
#wd="C:/Users/hubleyb/Documents/Halibut/Git/DataInputs/"
#datadir="C:/Users/harperd/Documents/Halibut/RDataVault"
#wd="C:/Users/harperd/Documents/Halibut/GitDataInputs/DataInputs/"
source(file.path(wd, "passwords.r"))
ds_all <- Mar.datawrangling::load_datasources()
devtools::load_all(".")


```

## Update data from database 

```{r}

# Update data from database 

#get_data(db='isdb',data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)

get_data(db='isdb',data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)
get_data(db='rv',data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)

get_data_custom(schema="observer", data.dir = datadir, tables = c("ISFISHLENGTHS","ISSAMPLES"), usepkg = "roracle",
                                     fn.oracle.dsn= "PTRAN", fn.oracle.username=uid, fn.oracle.password =pwd)
```

### SUrvey ABundance Indices
## prepare Data for hook occupancy model

```{r }
HookOccupancyData<-PrepareDataHookModel()

```

### Size Composition 
## Prepare data for Length Frequemcy plots

```{r, echo=FALSE}
bins=seq(0,260,5)

FixedSurvey<-FixedSurveyData(datadir=datadir,by.sex=T, bins=bins, LF.from = "ISFISH")
FixedSurvey2<-FixedSurveyData(datadir=datadir,by.sex=T, bins=bins, LF.from = "ISFISHLENGTHS")

RandomSurvey<-RandomSurveyData(sp=30,datadir=datadir,add.gear=T,add.LF=T,bins=bins,by.sex=T,hook.data=T)
RandomSurvey2<-RandomSurveyData(sp=30,datadir=datadir,add.LF=T,bins=bins,by.sex=F)

ComIndex<-CommercialIndexData(datadir=datadir,bins=bins,add.portsampling=T)
```

## Map Fixed stations
```{r}
xl=c(-69,-47)
yl=c(40,48)    
stations_100 <- read.csv(file.path(wd,'data',"FixedStation100.csv"))

  pdf(file.path(wd,'figures','FixedStationSurveyMap.pdf'),width=10,height=7)
                         
SpatialHub::bioMap(xlim = xl, ylim = yl, mapRes="MR", title = "Fixed Station Survey")
points(LATITUDE~LONGITUDE,FixedSurvey2,pch=16,col=rgb(0,0,0,0.2),cex=0.5)
points(lat.DecDeg~lon.DecDeg,stations_100,pch=21,bg=rgb(1,1,0,0.8))

dev.off()



```

## Map Random stations
```{r}
xl=c(-69,-47)
yl=c(40,48)    
#stations_100 <- read.csv(file.path(wd,'data',"FixedStation100.csv"))

  pdf(file.path(wd,'figures','StratfiedRandomSurveyMap2020.pdf'),width=10,height=7)
                         
SpatialHub::bioMap(xlim = xl, ylim = yl, mapRes="MR", title = "Fixed Station Survey")
points(LATITUDE~LONGITUDE,subset(RandomSurvey2,YEAR==2020),pch=21,bg=rgb(1,1,0,1))

dev.off()



```


## Construct LF for plots
```{r}
  Yrs1 = 2009:2020        
  Yrs2 = 2017:2020        
  
  #subset by nafo
  #nafos<-unique(FixedSurvey$NAFAREA_ID)
  #nafo4x <- nafos[c(grep('4X',nafos),grep('4V',nafos),grep('4W',nafos))]
  #FixedSurvey4X <-subset(FixedSurvey,NAFAREA_ID%in%nafo4x)
  
  #scale LF
  #FixedSurvey$N_MEASURED <- rowSums(FixedSurvey[,bins])
  #x$scaler = x$NUM_HOOK_HAUL/1000 

  # Construct CLF
  fixedLF=constructLF(LFdata=FixedSurvey,bins=bins, Yrs = Yrs1)
  fixedLF2=constructLF(LFdata=FixedSurvey2,bins=bins, Yrs = Yrs1)
  RandomLF=constructLF(LFdata=RandomSurvey,bins=bins, Yrs = Yrs2)
  ComIndexLF=constructLF(LFdata=ComIndex,bins=bins, Yrs = Yrs1)

  

```


## LF plots
```{r}

    BarPlotLF(fixedLF,yrs=Yrs1,rel=T,filen=file.path(wd,"figures","fixedLF1"))
    BarPlotLF(fixedLF2,yrs=Yrs1,rel=T,filen=file.path(wd,"figures","fixedLF2"))
    BarPlotLF(fixedLF,yrs=Yrs1,rel=F,filen=file.path(wd,"figures","fixedLF"),ymax=320)
  
    BarPlotLF(RandomLF,yrs=Yrs2,rel=T,filen=file.path(wd,"figures","randomLF1"))
    BarPlotLF(RandomLF,yrs=Yrs2,rel=F,filen=file.path(wd,"figures","randomLF2"),ymax=150)
    
    BarPlotLF(ComIndexLF,yrs=Yrs1,rel=T,filen=file.path(wd,"figures","comindexLF1"))
    BarPlotLF(ComIndexLF,yrs=Yrs1,rel=F,filen=file.path(wd,"figures","comindexLF2"),ymax=1400)


```
## Checking data for mis match in EST_NUM_CAUGHT and NUM_MEASURED

```{r}


SR20=subset(RandomSurvey,NUM_MEASURED!=EST_NUM_CAUGHT&YEAR==2020)

#FS20=subset(FixedSurvey, NUM_MEASURED!=EST_NUM_CAUGHT&YEAR==2020) 
##maybe they don't have to measure all ones caught in the fixed survey stations?

RandomSurvey$N_MEASURED <- rowSums(RandomSurvey[,paste0("L",bins[-1])])
x20=subset(RandomSurvey,NUM_MEASURED!=EST_NUM_CAUGHT&YEAR==2020)


SR20 <- SR20 %>%
  select("FISHSET_ID", "SET_NO", "TRIP_ID", "STATION", "EST_NUM_CAUGHT", "EST_COMBINED_WT", "SEXCD_ID", "NUM_MEASURED", "TRIP", "VESS_ID", "VESSEL_NAME", "CFV")
print(SR20)
```
## LF plots
```{r}
  
    BarPlotLF(fixedLF,yrs=Yrs,rel=T,filen=file.path(wd,"figures","fixedLF1"))
    BarPlotLF(fixedLF,yrs=Yrs,rel=F,filen=file.path(wd,"figures","fixedLF2"),ymax=320)
  
    BarPlotLF(RandomLF,yrs=Yrs,rel=T,filen=file.path(wd,"figures","randomLF1"))
    BarPlotLF(RandomLF,yrs=Yrs,rel=F,filen=file.path(wd,"figures","randomLF2"),ymax=150)
    
    BarPlotLF(ComIndexLF,yrs=2009:2020,rel=T,filen=file.path(wd,"figures","comindexLF1"))
    BarPlotLF(ComIndexLF,yrs=2009:2020,rel=F,filen=file.path(wd,"figures","comindexLF2"),ymax=1400)


```


## RV survey

```{r}
RVSurvey<-RVSurveyData(uid, pwd, bins=bins, by.sex=T,use.local=F,datadir=data.dir)
RVSurvey<-RVSurveyData(uid, pwd, bins=bins, by.sex=T,use.local=T,datadir=data.dir)
  
rvLF=constructLF(LFdata=RVSurvey,bins=bins, Yrs = Yrs1)
    
BarPlotLF(rvLF,yrs=Yrs1,rel=T,filen=file.path(wd,"figures","RVLF1"))
BarPlotLF(rvLF,yrs=Yrs1,rel=F,filen=file.path(wd,"figures","RVLF2"),ymax=50)

```
