---
title: "Update Advice"
author: "Brad"
date: "2022-10-13"
output: html_document
---


```{r setup, include=FALSE}
library(ROracle)
library(devtools)
library(tidyverse)
library(PBSmapping)
source(file.path(getwd(), "directories.r"))
source(file.path(wd, "passwords.r")) 

ds_all <- Mar.datawrangling::load_datasources()

devtools::load_all(".")

bins=seq(0,260,5)
# labelled by upper bound


Assessment.Year <- 2024


```


## Update data from database 

```{r }


# Update data from database 

# Mar.datawrangling::get_data(db='isdb',data.dir=datadir,fn.oracle.username = uid, fn.oracle.password = pwd, fn.oracle.dsn = 'ptran',usepkg='roracle',force.extract=T)
# open and check setprofile_wide to confirm that you have year, latitude & longitude

# RVdata<-get4VWXRV(uid, pwd, use.local=F,datadir=datadir)

```
# Landings
```{r}

  tl.df=data.frame(
    panel.category = rep("Catch",nrow(Catch)),
    year = Catch$Year,
    ts.name = Catch$Source,
    ts.value = Catch$landings_mt)

  # top-left panel - Catch and TAC
  yl <- c(0, max(tl.df$ts.value,na.rm=T) * 1.2)
  colrs<-c('#377eb8','#d53e4f','#7fbc41')

    x.lab <- "Year"
    y.lab <- "Catch (T)"
    legend.text <- c("Canada","Foreign", "TAC")

  y1<-min(tl.df$year)
  plm<-pivot_wider(tl.df,names_from = year, values_from = ts.value)
  plm<-as.matrix(plm[c(1,2,4),-(1:2)])
  plm[is.na(plm)]<-0


  barplot(plm,ylim=yl, axes = FALSE, col=c(colrs[1],colrs[2],colrs[1]),border=NA,density=c(NA,NA,40),axisnames=F)
  #axis(1,at=seq(0.7,(Assessment.Year-1959)*1.2,1.2),lab=F,tck=-0.01) ##change to 77 in sequence to increase axis length (ticks)
  axis(1,at=seq(0.7,(Assessment.Year-y1+1)*1.2,12),lab=seq(y1,Assessment.Year,10))##75 remains (no change) since 2023 not a multiple of 10
  axis(2, at = seq(0, yl[2], 1000), las = 1,
       labels = prettyNum(seq(0, yl[2],1000),
                          big.mark = ',',
                          scientific = FALSE))
  lines(seq(0.7,(Assessment.Year-y1+1)*1.2,1.2),in.df$ts.value[in.df$ts.name=="TAC"],col=colrs[3],lwd=3) ##change to 78 to accommodate additional year
  #legend("topright","(A)", bty = "n", cex=1.25)
  legend('topleft',
         legend.text,
         pch=c(15,15,NA),
         col=c(colrs[1],colrs[2],colrs[3]),
         lwd=c(NA,NA,3),
         box.lty=0,
         bg=NA,
         cex=0.8)

  mtext(side = 1, x.lab, line = 2, cex = 1)
  mtext(side = 2, y.lab, line = 3.2, cex = 1)
  box()

```



#NS RV survey

```{r}
#RVdata<-get4VWXRV(uid, pwd, use.local=F,datadir=datadir)
RVdata<-get4VWXRV(uid, pwd, use.local=F,datadir=datadir)

RVinputs<-prepRVdata(RVdata,bins=bins,years=1970:Assessment.Year, raw=T)

RVinputs$NSRV_unsexed<-RVinputs$NSRV_combined-(RVinputs$NSRV_males+RVinputs$NSRV_females) # unsexed
NSRV_Index<-RVinputs$Index
NSRV_Lengths<-list(NSRV_males=RVinputs$NSRV_males,
                   NSRV_females=RVinputs$NSRV_females,
                   NSRV_combined=RVinputs$NSRV_combined,
                   NSRV_unsexed=RVinputs$NSRV_unsexed)


## data for comparing 4X and 4VSW

strata4x<-c(470:495)
RVinputs4X<-prepRVdata(RVdata,strat=strata4x,bins=bins,years=1970:Assessment.Year, raw=T)

strata4VSW<-c(440:469)
RVinputs4VSW<-prepRVdata(RVdata,strat=strata4VSW,bins=bins,years=c(1970:Assessment.Year), raw=T)


NSRV_Lengths4X<-list(NSRV_males=RVinputs4X$NSRV_males,
                   NSRV_females=RVinputs4X$NSRV_females,
                   NSRV_combined=RVinputs4X$NSRV_combined)

NSRV_Lengths4VSW<-list(NSRV_males=RVinputs4VSW$NSRV_males,
                   NSRV_females=RVinputs4VSW$NSRV_females,
                   NSRV_combined=RVinputs4VSW$NSRV_combined)

# 
#NSRV_Index$NPT[NSRV_Index$year==2021]<-NA
```


# length frequency plots

```{r}
BubblePlotLF(NSRV_Lengths,bins=bins,yrs=1970:Assessment.Year,path=file.path(wd,'figures'),filen='NLRVSurvey',inches=0.3)

nsrvl<-revNAL(NSRV_Lengths[-3])
YrsObs = (Assessment.Year-29):Assessment.Year 
BarPlotLF(nsrvl[which(names(nsrvl)%in%YrsObs)],yrs=YrsObs,rel=F,filen=file.path(wd,"figures","NSRVbarplot"),rows=15,graphic='png',ax=c(rep(2,15),rep(4,15)))

#4X
BubblePlotLF(NSRV_Lengths4X,bins=bins,yrs=1970:Assessment.Year,path=file.path(wd,'figures'),filen='NLRVSurvey4X',inches=0.3)

nsrvl<-revNAL(NSRV_Lengths4X[-3])
YrsObs = (Assessment.Year-29):Assessment.Year 
BarPlotLF(nsrvl[which(names(nsrvl)%in%YrsObs)],yrs=YrsObs,rel=F,filen=file.path(wd,"figures","NSRVbarplot4X"),rows=15,graphic='png',ax=c(rep(2,15),rep(4,15)))

#4VSW
BubblePlotLF(NSRV_Lengths4VSW,bins=bins,yrs=c(1970:Assessment.Year),path=file.path(wd,'figures'),filen='NLRVSurvey4VSW',inches=0.3)

nsrvl<-revNAL(NSRV_Lengths4VSW[-3])
YrsObs =c((Assessment.Year-29):Assessment.Year) 
BarPlotLF(nsrvl[which(names(nsrvl)%in%YrsObs)],yrs=YrsObs,rel=F,filen=file.path(wd,"figures","NSRVbarplot4VSW"),rows=15,graphic='png',ax=c(rep(2,15),rep(4,15)))


```

#Halibut Longline Survey

```{r}

  # old fixed station index, discontinued in 2023
  HSFixed_Index<-FixedSurveyIndex(datadir=datadir,yrs=1998:2022)

  # stratified random index as designed
  HSRandom_Index<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:Assessment.Year)
  
  # stratified random index without zero strata
  HSRandom_Index2<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:Assessment.Year, 
                                               ZeroStrata=F, restratify=F)
  
   # stratified random index without zero strata and combining 52 and 53 for all years 
  HSRandom_Index4<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:Assessment.Year, 
                                               ZeroStrata=F,  restratify=F, combine.strata=52:53)
  
  # stratified random index with zero strata restratified and combining 52 and 53 for all years 
  HSRandom_Index5<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:Assessment.Year, 
                                               ZeroStrata=T, restratify=T, combine.strata=52:53)
  
  
  with(subset(HSRandom_Index,Year==Assessment.Year),c(KgPKH,KgPKH-KgPKHse*1.96,KgPKH+KgPKHse*1.96))/2

```

# Harvest Control Rule
```{r}
value <- HSRandom_Index$mean3_biomass[HSRandom_Index$Year==Assessment.Year]
HCR(value)
#HCR(value, q=0.0019) # when using calculated weight

#        2022     2023     2024     2025     2026     2027     2028     2029     2030     2031     2032
#5%  38.83043 35.71793 33.53717 31.94565 30.82011 29.21892 27.36027 25.93016 25.20165 24.37584 24.27301
#50% 45.86816 43.79167 41.72372 39.26645 38.06372 36.05268 36.90610 34.27920 31.97353 29.82158 29.37683
#95% 53.69893 53.00915 52.51613 51.23453 48.62486 48.71512 51.15732 53.86223 56.16071 54.92724 56.06781


```


## plot survey indices SSR version
```{r}
#RVinputs$Index
png(file.path(wd,'figures',"ModelindicesSSR2.png"), width =8, height = 6,units='in',pointsize=12, res=300,type='cairo')
par(mfcol=c(2,1), mar = c(0,4,0,0.5), omi = c(0.5, 0.25, 0.5, 0.25),las=1)

plot(NPT~year,NSRV_Index, ylab="Number / tow", xlab = '', ylim=c(0,max(NPT,na.rm=T)*1.2), type='o',pch=16,xlim=c(1970,Assessment.Year),xaxt='n')
axis(1,lab=F)
points(c(2018,2021,2022),NSRV_Index$NPT[NSRV_Index$year%in%c(2018,2021,2022)],col='red',cex=2)

plot(KgPKH~Year,HSFixed_Index,type='l',pch=16,col='grey',lty=2,ylim=c(0,255),xlim=c(1970,Assessment.Year), ylab="Kg / 1000 hooks")
lines(mean3_biomass~Year,HSFixed_Index)
lines(KgPKH~Year,HSRandom_Index,type='o',pch=16,col='blue')
#lines(KgPKH+KgPKHse~Year,HSRandom_Index,lty=2,col='blue')
#lines(KgPKH-KgPKHse~Year,HSRandom_Index,lty=2,col='blue')
lines(mean3_biomass~Year,HSRandom_Index,lwd=3)

dev.off()


```


# compare 4X and 4VSW in RV survey
```{r}
png(file.path(wd,'figures',"RVsurvey4Xvs4VSW.png"), width =8, height = 6,units='in',pointsize=12, res=300,type='cairo')
par(mfcol=c(2,1), mar = c(0,4,0,0.5), omi = c(0.5, 0.25, 0.5, 0.25),las=1)

plot(B/tunits~year,RVinputs4X$Index, ylab="Kg / tow", xlab = '', ylim=c(0,5), type='o',pch=16,xlim=c(1970,Assessment.Year),xaxt='n')
lines(B/tunits~year,RVinputs4VSW$Index,type='o',pch=15,col=2)


plot(NPT~year,RVinputs4X$Index, ylab="Number / tow", xlab = '', ylim=c(0,max(NPT,na.rm=T)*1.2), type='o',pch=16,xlim=c(1970,Assessment.Year))
lines(NPT~year,RVinputs4VSW$Index,type='o',pch=15,col=2)

dev.off()


```

# Comparing calculated weight vs estimated weight
```{r}
 HSRandom_Index<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:Assessment.Year,use.calc.weight = F)
 HSRandom_Index2<-StratifiedRandomSurveyIndex(datadir=datadir,yrs=2017:Assessment.Year,use.calc.weight = T)

```



```{r}
 plot(KgPKH~Year,HSRandom_Index4,ylim=c(0,150),type='l',lwd=2)
 with(HSRandom_Index4,lines(Year,mean3_biomass,lty=2))
 with(HSRandom_Index5,lines(Year,KgPKH,lwd=2,col=2))
 with(HSRandom_Index5,lines(Year,mean3_biomass,lty=2,col=2))
 
 # Q-adjusted
 plot(KgPKH/0.002~Year,HSRandom_Index,ylim=c(0,60000),type='l',lwd=2,ylab="Biomass")
 with(HSRandom_Index,lines(Year,mean3_biomass/0.002,lty=2))
 with(HSRandom_Index2,lines(Year,KgPKH/0.0019,lwd=2,col=2))
 with(HSRandom_Index2,lines(Year,mean3_biomass/0.0019,lty=2,col=2))
 
 # Q-adjusted
 plot(KgPKH/4.6~Year,HSFixed_Index,ylim=c(0,60),type='l',lwd=2,ylab="Biomas (kt)",las=1)
 #with(HSFixed_Index,lines(Year,mean3_biomass/0.0046,lty=2))
 with(HSRandom_Index,lines(Year,KgPKH/2,lwd=2,col=2))
# with(HSRandom_Index,lines(Year,mean3_biomass/0.002,lty=2,col=2))
 
 
 
```

